name: elmada
channels:
  - conda-forge
  - anaconda
dependencies:  # NOTE: here '=' (single)
  - appdirs
  - black
  - bs4
  - entsoe-py=0.2.10
  - ipython
  - iso3166
  - isort
  - lxml
  - matplotlib
  - mypy
  - numpy
  - pandas
  - pip
  - plotly
  - pyarrow
  - pytest
  - pytest-cov
  - pytest-mock
  - python>=3.7
  - quandl
  - requests
  - scipy
  - xlrd
  # - notebook
  - pip:  # NOTE: here '==' (double)
    - pytest-responsemock
    - '--editable=.[dev]' # installs an editable full version of elmada