name: elmada
channels:
  - conda-forge
  - anaconda
dependencies:
  - appdirs
  - bs4
  - entsoe-py=0.2
  - ipython
  - lxml
  - matplotlib
  - numpy
  - pandas
  - pytables
  - python=3.7
  - quandl
  - requests
  - scipy
  - seaborn
  - xlrd
  - pip
  - pip:
    - '--editable=.[all]' # installs an editable version of elmada including feature dependencies