name: elmada
channels:
  - conda-forge
  - anaconda
dependencies:
# NOTE: here '=' (single)
  - appdirs
  - bs4
  - fastparquet
  - ipython
  - lxml
  - matplotlib
  - numpy
  - pandas
  - pip
  - plotly
  - pyarrow
  - pytables
  - pytest
  - pytest-cov
  - pytest-mock
  - python-snappy
  - python>=3.7
  - quandl
  - requests
  - scipy
  - seaborn
  - xlrd
  # - notebook
  - pip:
  # NOTE: here '==' (double)
    - entsoe-py==0.2
    - '--no-cache-dir --no-deps --editable .' # installs an editable version of elmada
