name: elmada
channels:
  - conda-forge
  - anaconda
dependencies:  # NOTE: here '=' (single)
  - appdirs
  - bs4
  - ipython
  - lxml
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyarrow
  - pytest
  - pytest-cov
  - pytest-mock
  - python>=3.7
  - quandl
  - requests
  - scipy
  - xlrd
  # - notebook
  - pip:  # NOTE: here '==' (double)
    - entsoe-py==0.2.10
    - '--editable=.[dev]' # installs an editable full version of elmada