name: CI with pip

on: push

jobs:
  unit-tests:
    name: Python ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "windows-latest"]
        python-version: [3.9] # 3.7, 3.8,
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Run pytest
      env:
        ENTSOE_API_KEY: ${{ secrets.ENTSOE_API_KEY }}
        MORPH_API_KEY: ${{ secrets.MORPH_API_KEY }}
        QUANDL_API_KEY: ${{ secrets.QUANDL_API_KEY }}
      shell: bash -l {0}
      run: |
        pytest -v -m="not apikey" .
