name: On push

on: [push]
# sources
# https://github.com/marketplace/actions/setup-conda
# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest, macOS-latest]
#         python-version: [3.6, 3.7, 3.8]
#     name: Python ${{ matrix.python-version }} example
#     steps:
#       - uses: actions/checkout@v2
#       - name: Setup conda
#         uses: s-weigand/setup-conda@v1
#         with:
#           update-conda: true
#           python-version: ${{ matrix.python-version }}
#           conda-channels: anaconda, conda-forge
#       - run: conda --version
#       - run: which python


jobs:
  unit-tests:
    name: Python ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9"]
    defaults:
      run:
        working-directory: ..
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: elmada
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - name: Test with pytest and generate coverage report
        run: |
          python -m pytest -v --cov=. --cov-report=xml .
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
